
package libraryclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LibraryServerImplBaseService", targetNamespace = "http://libraryserver/", wsdlLocation = "http://localhost:7777/libraryserver?wsdl")
public class LibraryServerImplBaseService
    extends Service
{

    private final static URL LIBRARYSERVERIMPLBASESERVICE_WSDL_LOCATION;
    private final static WebServiceException LIBRARYSERVERIMPLBASESERVICE_EXCEPTION;
    private final static QName LIBRARYSERVERIMPLBASESERVICE_QNAME = new QName("http://libraryserver/", "LibraryServerImplBaseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/libraryserver?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIBRARYSERVERIMPLBASESERVICE_WSDL_LOCATION = url;
        LIBRARYSERVERIMPLBASESERVICE_EXCEPTION = e;
    }

    public LibraryServerImplBaseService() {
        super(__getWsdlLocation(), LIBRARYSERVERIMPLBASESERVICE_QNAME);
    }

    public LibraryServerImplBaseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIBRARYSERVERIMPLBASESERVICE_QNAME, features);
    }

    public LibraryServerImplBaseService(URL wsdlLocation) {
        super(wsdlLocation, LIBRARYSERVERIMPLBASESERVICE_QNAME);
    }

    public LibraryServerImplBaseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIBRARYSERVERIMPLBASESERVICE_QNAME, features);
    }

    public LibraryServerImplBaseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibraryServerImplBaseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LibraryServer
     */
    @WebEndpoint(name = "LibraryServerImplBasePort")
    public LibraryServer getLibraryServerImplBasePort() {
        return super.getPort(new QName("http://libraryserver/", "LibraryServerImplBasePort"), LibraryServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LibraryServer
     */
    @WebEndpoint(name = "LibraryServerImplBasePort")
    public LibraryServer getLibraryServerImplBasePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://libraryserver/", "LibraryServerImplBasePort"), LibraryServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIBRARYSERVERIMPLBASESERVICE_EXCEPTION!= null) {
            throw LIBRARYSERVERIMPLBASESERVICE_EXCEPTION;
        }
        return LIBRARYSERVERIMPLBASESERVICE_WSDL_LOCATION;
    }

}
